/**
 * Code generated by protoc-gen-twirp_js v5.0.0, DO NOT EDIT.
 * source: command.proto
 */
// import our twirp js library dependency
var createClient = require("twirp");
// import our protobuf definitions
var pb = require("./command_pb.js");
Object.assign(module.exports, pb);

/**
 * Creates a new RoomServiceClient
 */
module.exports.createRoomServiceClient = function(baseurl, extraHeaders, useJSON) {
    var rpc = createClient(baseurl, "tmp.RoomService", "v5.0.0",  useJSON, extraHeaders === undefined ? {} : extraHeaders);
    return {
        /**
         * rpc debug(DebugRequest) returns (DebugResponse) {} 
         */
        listRoom: function(data) { return rpc("ListRoom", data, pb.ListRoomResponse); },
        createRoom: function(data) { return rpc("CreateRoom", data, pb.CreateRoomResponse); },
        deleteRoom: function(data) { return rpc("DeleteRoom", data, pb.DeleteRoomResponse); }
    }
}

